hooks:
  createImageAndDeleteImageVM:
    - webDriver: FindElement
      description: 'Click checkbox VM' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Create Image VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#create-image-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 10s'
      timeout: 10
    - webDriver: FindElement
      description: 'Tìm ô image name và điền tên.' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: '#image-name'
        ignored: True
      actions:
        - action: Sendkeys #đánh chữ vào ô input
          value: 'image-Ubuntu-SE-Random'
    - webDriver: ExecuteScript
      description: 'Click Accept tạo image cho VM'
      script: document.querySelector('a[ng-click="acceptCreateImage()"]').click()
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 120s'
      timeout: 120
    - webDriver: AccessNewUrl # chụp màng hình
      description: 'Mở BlockStore'
      newUrl: 'https://portal3.vngcloud.vn/volumes/list.html'
    - webDriver: FindElement
      description: 'click image ở left-menu' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: a[onclick="location.href='/images/list.html'"]
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input'
    - webDriver: FindElement
      description: 'Click checkbox image' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//*[@id="user-image-list"]//div[contains(text(),"image-Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'click delete image ở trong menu Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: '#delete-image-btn'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input'
    - webDriver: ExecuteScript
      description: 'Xác nhận việc delete image'
      script: document.querySelector('a[ng-click="acceptDeleteImage()"]').click()
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 10s'
      timeout: 10
    - webDriver: AccessNewUrl # chụp màng hình
      description: 'Mở BlockStore'
      newUrl: 'https://portal3.vngcloud.vn/volumes/list.html'
    - webDriver: FindElement
      description: 'Click thùng rác' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'span.headerNumber.trashItemNumber'
        ignored: True
      actions:
        - action: Click
    - webDriver: ExecuteScript
      description: 'Delete image trong thùng rác'
      script: document.querySelector('tr[resourcename="image-Ubuntu-SE-Random"]>td#doDelete>i.fa-trash').click()
    - webDriver: FindElement
      description: 'Click Confirm Delete VM trong thùng rác' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: '.btn-accept-remove-resource'
        ignored: True
      actions:
        - action: Click
    - webDriver: Screenshot # chụp màng hình
      description: 'Chụp hình màn hình server'