hooks:
  waitingAndCheck:
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 120s'
      timeout: 120
    - webDriver: SetImplicitWaitTimeout #set timeout bắt element
      description: 'Thực hiện Implicit Wait Timeout trong vòng 60s'
      timeout: 60
    - webDriver: FindElement
      description: 'Tìm VM mà ta muốn check status' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'input[ng-model="filterSearchText"]'
        ignored: True
      actions:
        - action: Sendkeys #đánh chữ vào ô input
          value: 'Ubuntu-SE-Random'
    - webDriver: FindElement
      description: 'Check VM mới Ubuntu-SE-Random tạo đã acitive hay chưa' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//following-sibling::div//following-sibling::div/div[1]'
        ignored: True
      actions:
        - action: Text
          check: ACTIVE
    - webDriver: FindElement
      description: 'Click checkbox VM' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Console VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#console-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 10s'
      timeout: 10
    - webDriver: SwitchWindow
      description: 'Chuyển tab'
      tab: 1