hooks:
  checkUpdateSecGroupVM:
    # - webDriver: FindElement
    #   description: 'Click checkbox VM' 
    #   webElement: 
    #     by: ByXPATH #tìm kí tự mong muốn
    #     value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
    #     ignored: True
    #   actions:
    #     - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Update Security VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#update-sec-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: Screenshot # chụp màng hình
      description: 'Chụp hình màn hình server'
    - webDriver: FindElement
      description: 'Click Input để list SecGroup' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "#allowed-method"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 10s'
      timeout: 10
    - webDriver: FindElement
      description: 'Click chọn SecGroup selenium' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//option[contains(text(),"selenium")]'
        ignored: True
      actions:
        - action: Text
        - action: Click
    - webDriver: FindElement
      description: 'Click chọn Update SecGroup' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Update")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click checkbox VM' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Update Security VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#update-sec-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Check Đã thêm SecGroup selenium hay chưa' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//div[contains(text(),"selenium")]'
        ignored: True
      actions:
        - action: Text
    - webDriver: ExecuteScript
      description: 'Click close Action Update Security'
      script: document.querySelector('#update-sec-modal > div > div > div > div:nth-child(3) > a.btn.btn-close.btn-tw').click()
    - webDriver: Screenshot # chụp màng hình
      description: 'Chụp hình màn hình server'