hooks:
  listVM:
    - webDriver: FindElement
      description: 'Tìm VM mà ta muốn' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'input[ng-model="filterSearchText"]'
        ignored: False
      actions:
        - action: Sendkeys #đánh chữ vào ô input
          value : 'test-se'
    - webDriver: FindElement
      description: 'Check VM mới tạo đã acitive' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"test-se")]'
        ignored: False
      actions:
        - action: Text
    # - webDriver: AccessNewUrl # chụp màng hình
    #   description: 'Truy cập link web mới'
    #   newUrl: 'https://sdn-portal.vngcloud.vn/ops/overview.html'
    - webDriver: Screenshot # chụp màng hình
      description: 'Chụp hình màn hình server'