hooks:
  checkResizeVM:
    - webDriver: FindElement
      description: 'Click checkbox VM' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Resize VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#resize-server-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElements
      description: 'Check list flavor và Click resize VM flavor random'
      webElement:
        by: ByCSSSelector
        value: 'tr.ng-scope[ng-repeat="flavor in filteredFlavors"] > td[ng-bind="flavor.name"]'
        ignored: True
      checkElements:
        countElements: 17
        memberOfElements:
          - value: v1.small2x8.b100
          - value: v1.small1x1.b100
          - value: v1.large24x64.b100
        declareElement4Click:
          style: random
          range: 4
      actions:
        - action: Click
        - action: Text
    - webDriver: FindElement
      description: 'Click Resize VM' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "#save-resize-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click Xac Nhan Resize VM' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: '[ng-click="resizeServer()"]'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 120s'
      timeout: 120
    - webDriver: FindElement
      description: 'Check Ubuntu-SE-Random tạo đã start hay chưa' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//following-sibling::div//following-sibling::div/div[1]'
        ignored: True
      actions:
        - action: Text
          check: ACTIVE